from ReadCredentialsAzure1.AzureCredentials import AzureCredentials
from ReadCredentialsAzure1.ResourceGroup import ResourceGroup
from ReadCredentialsAzure1.AvailabilitySet import AvailabilitySet
from ReadCredentialsAzure1.VirtualNet import VirtualNet
from ReadCredentialsAzure1.Subnet import Subnet
from ReadCredentialsAzure1.VirtualMachine import VirtualMachine

